package com.littlehotel.littleHotelServer.utility;

import java.util.ArrayList;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.validation.FieldError;

import com.littlehotel.littleHotelServer.model.ErrorResponse;
import com.littlehotel.littleHotelServer.model.SubError;

/**
 * Static Utility methods for handling validations, generating response messages
 * 
 * @author Sharad Shrestha
 *
 */
public class Utils {

	/*
	 * Method to generate response message for field validation errors for post
	 * request
	 * 
	 * @param status String
	 * 
	 * @param message String
	 * 
	 * @param fieldErrors a list of FieldErrors generated by validation plugin used
	 * 
	 * @return ErrorResponse
	 * 
	 */
	public static ErrorResponse createErrorResponse(HttpStatus status, String message, List<FieldError> fieldErrors) {

		ErrorResponse errorResponse = new ErrorResponse();
		errorResponse.setStatus(status);
		errorResponse.setMessage(message);
		List<SubError> errors = new ArrayList<>();

		if (fieldErrors != null) {
			fieldErrors.forEach(fieldError -> {
				SubError subError = new SubError();
				subError.setObject(fieldError.getObjectName());
				subError.setField(fieldError.getField());
				subError.setMessage(fieldError.getDefaultMessage());
				subError.setRejectedValue((String) fieldError.getRejectedValue());
				errors.add(subError);
			});
		}
		errorResponse.setErrors(errors);
		return errorResponse;
	}


}
